# Generated by Django 2.1.1 on 2018-10-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180926_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='registration',
            name='gst_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
