# Generated by Django 2.1.1 on 2018-10-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20181023_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
