# Generated by Django 2.1.1 on 2018-10-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20181023_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='txnid_pg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
