# Generated by Django 2.1.1 on 2018-10-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registration_txnid_pg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fees', models.FloatField(default=0.0)),
                ('gst_amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='purpose_of_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.PaymentTypes'),
        ),
    ]
