# Generated by Django 2.1.1 on 2018-11-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20181102_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='txn_method',
            field=models.CharField(blank=True, choices=[('BillDesk', 'BillDesk'), ('Cash', 'Cash'), ('NEFT/IMPS/RTGS', 'NEFT/IMPS/RTGS'), ('Cheque', 'Cheque')], max_length=50, null=True),
        ),
    ]
