# Generated by Django 2.1.1 on 2018-11-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20181102_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttypes',
            name='hidden',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
