# Generated by Django 2.1.3 on 2018-11-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20181113_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttypes',
            name='hsnsac',
            field=models.CharField(blank=True, default='None', max_length=150, null=True),
        ),
    ]
