# Generated by Django 2.1.3 on 2018-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_paymenttypes_hsnsac'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='invoice_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
