# Generated by Django 2.1.3 on 2018-11-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_registration_invoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='invoice_file',
        ),
    ]
