# Generated by Django 2.1.3 on 2018-11-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_remove_registration_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='send_invoice',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
