# Generated by Django 2.1.3 on 2018-11-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_remove_registration_send_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='invoice',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='invoices'),
        ),
    ]
