# Generated by Django 2.1.3 on 2018-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_registration_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
