# Generated by Django 2.1.3 on 2018-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_registration_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='taxable amount'),
        ),
    ]
