# Generated by Django 2.1.3 on 2018-12-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_auto_20181206_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='amount',
            new_name='taxable_amount',
        ),
    ]
