# Generated by Django 2.1.3 on 2018-12-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20181206_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
