# Generated by Django 2.1.3 on 2019-01-04 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20181206_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccesfullRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('ipa_enrollment_number', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=150, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry')], default='Delhi', max_length=25)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(default='India', max_length=150)),
                ('landline', models.BigIntegerField(blank=True, null=True)),
                ('txn_status', models.CharField(blank=True, max_length=50, null=True)),
                ('txnid', models.CharField(blank=True, max_length=50, null=True)),
                ('txnid_pg', models.CharField(blank=True, max_length=50, null=True)),
                ('txn_method', models.CharField(blank=True, choices=[('BillDesk', 'BillDesk'), ('Cash', 'Cash'), ('NEFT/IMPS/RTGS', 'NEFT/IMPS/RTGS'), ('Cheque', 'Cheque')], max_length=50, null=True)),
                ('taxable_amount', models.FloatField(default=0.0, verbose_name='taxable amount')),
                ('igst', models.FloatField(blank=True, null=True)),
                ('cgst', models.FloatField(blank=True, null=True)),
                ('sgst', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('invoice', models.FileField(blank=True, max_length=150, null=True, upload_to='invoices')),
                ('purpose_of_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.PaymentTypes')),
            ],
        ),
    ]
