# Generated by Django 2.1.3 on 2019-01-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_auto_20190104_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='succesfullregistration',
            name='invoice_series',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
